import { uid } from './constants';
import type { Flavour, FlavourComponent, StockMap } from './types';

function flavour(partial: Partial<Flavour> & Pick<Flavour, 'name' | 'group' | 'groupOrder'>): Flavour {
  return {
    id: uid('fl'),
    active: true,
    isSpecial: false,
    popular: false,
    par: 2,
    yieldPotsPerBladder: 2.5,
    prodTimeMinPerBladder: 15,
    allergenNotes: '',
    washAlwaysAfter: false,
    notes: '',
    photoRef: '',
    groupUnconfirmed: false,
    components: [],
    ...partial,
  };
}

function comp(name: string, needsBaking = false): FlavourComponent {
  return { id: uid('cmp'), name, needsBaking };
}

/** Seed catalogue — faithful port of the Claude artifact. */
export function seedFlavours(): Flavour[] {
  return [
    flavour({ name: 'Choc mint', group: 'A', groupOrder: 1, par: 2, yieldPotsPerBladder: 1.5 }),
    flavour({
      name: 'Pistachio',
      group: 'B',
      groupOrder: 1,
      par: 2,
      yieldPotsPerBladder: 2.5,
      allergenNotes: 'Contains tree nuts (pistachio).',
    }),
    flavour({
      name: 'Pistachio praline',
      group: 'C',
      groupOrder: 1,
      popular: true,
      par: 3,
      yieldPotsPerBladder: 2.5,
      allergenNotes: 'Contains tree nuts (pistachio).',
      components: [comp('Pistachio base bladder'), comp('Pistachio paste')],
    }),
    flavour({
      name: 'Vanilla',
      group: 'C',
      groupOrder: 2,
      popular: true,
      par: 3,
      yieldPotsPerBladder: 3.5,
      allergenNotes: 'Dairy.',
    }),
    flavour({
      name: 'Hokey pokey',
      group: 'C',
      groupOrder: 3,
      par: 2,
      yieldPotsPerBladder: 3,
      allergenNotes: 'Dairy.',
    }),
    flavour({ name: 'Salted caramel', group: 'C', groupOrder: 4, par: 2, yieldPotsPerBladder: 3 }),
    flavour({
      name: 'Super dulce de leche',
      group: 'C',
      groupOrder: 5,
      par: 2,
      yieldPotsPerBladder: 2.5,
    }),
    flavour({
      name: 'Cookies and cream',
      group: 'C',
      groupOrder: 6,
      par: 2,
      yieldPotsPerBladder: 2,
      allergenNotes: 'Contains gluten (biscuit).',
      components: [comp('Vanilla base bladder'), comp('Crushed biscuit mix-in')],
    }),
    flavour({
      name: 'Choc chip',
      group: 'C',
      groupOrder: 7,
      par: 2,
      yieldPotsPerBladder: 3,
      allergenNotes: 'Contains gluten (biscuit) — confirm recipe.',
    }),
    flavour({
      name: 'Tiramisu',
      group: 'C',
      groupOrder: 8,
      popular: true,
      par: 3,
      yieldPotsPerBladder: 2.5,
      allergenNotes: 'Contains egg, alcohol (marsala).',
    }),
    flavour({
      id: 'coffee',
      name: 'Coffee',
      group: 'C',
      groupOrder: 9,
      par: 2,
      yieldPotsPerBladder: 3,
      notes:
        'Last in Group C. If churned, the machine must be washed before starting Group D. If not churned, Group D can continue without a wash.',
    }),
    flavour({
      name: 'Macadamia',
      group: 'D',
      groupOrder: 1,
      par: 2,
      yieldPotsPerBladder: 2.5,
      allergenNotes: 'Contains tree nuts (macadamia).',
      notes: 'First flavour of Group D — wash only required beforehand if Coffee was churned.',
      components: [
        comp('Nut base bladder'),
        comp('Macadamia paste'),
        comp('Macadamia crunch', true),
      ],
    }),
    flavour({
      name: 'White choc hazelnut',
      group: 'D',
      groupOrder: 2,
      par: 2,
      yieldPotsPerBladder: 2.5,
      allergenNotes: 'Contains tree nuts (hazelnut).',
    }),
    flavour({
      name: 'Hazelnut',
      group: 'D',
      groupOrder: 3,
      par: 2,
      yieldPotsPerBladder: 2.5,
      allergenNotes: 'Contains tree nuts (hazelnut).',
    }),
    flavour({
      name: 'Milk choc peanut fudge',
      group: 'D',
      groupOrder: 4,
      popular: true,
      par: 3,
      yieldPotsPerBladder: 2.5,
      allergenNotes: 'Contains peanuts.',
    }),
    flavour({
      name: 'Messinatella',
      group: 'D',
      groupOrder: 5,
      par: 2,
      yieldPotsPerBladder: 2.2,
      prodTimeMinPerBladder: 20,
    }),
    flavour({
      name: 'Fondant',
      group: 'D',
      groupOrder: 6,
      popular: true,
      par: 3,
      yieldPotsPerBladder: 1.5,
    }),
    flavour({
      name: 'Salted coconut and mango',
      group: 'E',
      groupOrder: 1,
      par: 2,
      yieldPotsPerBladder: 2.8,
      allergenNotes: 'Contains coconut.',
    }),
    flavour({
      name: 'Pandan and coconut',
      group: 'E',
      groupOrder: 2,
      par: 2,
      yieldPotsPerBladder: 3,
      allergenNotes: 'Contains coconut.',
    }),
    flavour({
      name: 'Coconut lychee',
      group: 'E',
      groupOrder: 3,
      par: 2,
      yieldPotsPerBladder: 3,
      allergenNotes: 'Contains coconut.',
    }),
    flavour({
      name: 'Bounty',
      group: 'E',
      groupOrder: 4,
      par: 2,
      yieldPotsPerBladder: 2.8,
      allergenNotes: 'Contains coconut.',
    }),
    flavour({
      name: 'Rum and raisin',
      group: 'F',
      groupOrder: 1,
      par: 2,
      yieldPotsPerBladder: 2.5,
      allergenNotes: 'Contains alcohol.',
    }),
    flavour({
      name: 'Blood orange',
      group: 'G',
      groupOrder: 1,
      par: 2,
      yieldPotsPerBladder: 4,
      prodTimeMinPerBladder: 10,
      notes: 'Dairy-free sorbet.',
    }),
    flavour({
      name: 'Strawberry',
      group: 'G',
      groupOrder: 2,
      par: 2,
      yieldPotsPerBladder: 4,
      prodTimeMinPerBladder: 10,
      notes: 'Dairy-free sorbet.',
    }),
    flavour({
      name: 'Strawberry and cream',
      group: 'G',
      groupOrder: 3,
      par: 2,
      yieldPotsPerBladder: 3,
      allergenNotes: 'Dairy.',
    }),
    flavour({
      name: 'Boysenberry',
      group: 'G',
      groupOrder: 4,
      par: 2,
      yieldPotsPerBladder: 4,
      prodTimeMinPerBladder: 10,
      notes: 'Dairy-free sorbet.',
    }),
    flavour({
      name: 'Lemon',
      group: 'H',
      groupOrder: 1,
      par: 2,
      yieldPotsPerBladder: 4,
      prodTimeMinPerBladder: 10,
      notes: 'Dairy-free sorbet.',
    }),
    flavour({
      name: 'Mango',
      group: 'H',
      groupOrder: 2,
      par: 2,
      yieldPotsPerBladder: 3.5,
      prodTimeMinPerBladder: 10,
      notes: 'Dairy-free sorbet.',
    }),
    flavour({
      name: 'Passionfruit',
      group: 'H',
      groupOrder: 3,
      par: 2,
      yieldPotsPerBladder: 4,
      prodTimeMinPerBladder: 10,
      notes: 'Dairy-free sorbet.',
    }),
    flavour({
      name: 'Choc sorbet',
      group: 'I',
      groupOrder: 1,
      par: 2,
      yieldPotsPerBladder: 3.5,
      prodTimeMinPerBladder: 10,
      notes: 'Dairy-free sorbet.',
    }),
    flavour({
      name: 'Cone-ception',
      group: 'J',
      groupOrder: 1,
      par: 2,
      yieldPotsPerBladder: 2.2,
      prodTimeMinPerBladder: 20,
      allergenNotes: 'Contains gluten (cone pieces) — confirm recipe.',
      notes: 'Guessed timing from the name — check this one first.',
    }),
    flavour({
      name: 'Bertha loves mertha',
      group: 'K',
      groupOrder: 1,
      isSpecial: true,
      groupUnconfirmed: true,
      notes: 'This month’s special — confirm group, allergens and yield.',
    }),
    flavour({
      name: 'Little bloke',
      group: 'K',
      groupOrder: 2,
      isSpecial: true,
      groupUnconfirmed: true,
      notes: 'This month’s special — confirm group, allergens and yield.',
    }),
    flavour({
      name: 'Blueberry cheesecake',
      group: 'L',
      groupOrder: 1,
      isSpecial: true,
      groupUnconfirmed: true,
      allergenNotes: 'Contains gluten (biscuit base) — confirm recipe.',
      notes: 'This month’s special — confirm group, allergens and yield.',
    }),
    flavour({
      name: 'Takking the mikki',
      group: 'L',
      groupOrder: 2,
      isSpecial: true,
      groupUnconfirmed: true,
      notes: 'This month’s special — confirm group, allergens and yield.',
    }),
    flavour({
      name: 'Breakfast in canberra',
      group: 'M',
      groupOrder: 1,
      isSpecial: true,
      groupUnconfirmed: true,
      notes: 'This month’s special — confirm group, allergens and yield.',
    }),
    flavour({
      name: 'The hat trick',
      group: 'M',
      groupOrder: 2,
      isSpecial: true,
      groupUnconfirmed: true,
      notes: 'This month’s special — confirm group, allergens and yield.',
    }),
    flavour({
      name: 'Crunch time',
      group: 'N',
      groupOrder: 1,
      isSpecial: true,
      groupUnconfirmed: true,
      allergenNotes: 'Likely contains gluten — confirm recipe.',
      notes: 'This month’s special — confirm group, allergens and yield.',
      components: [comp('Base bladder'), comp('Crunch topping', true)],
    }),
    flavour({
      name: 'You make me unicorny',
      group: 'N',
      groupOrder: 2,
      isSpecial: true,
      groupUnconfirmed: true,
      notes: 'This month’s special — confirm group, allergens and yield.',
    }),
    flavour({
      name: 'Finger bun',
      group: 'O',
      groupOrder: 1,
      isSpecial: true,
      groupUnconfirmed: true,
      allergenNotes: 'Likely contains gluten — confirm recipe.',
      notes: 'This month’s special — confirm group, allergens and yield.',
    }),
    flavour({
      name: 'Kinder swindler',
      group: 'P',
      groupOrder: 1,
      isSpecial: true,
      groupUnconfirmed: true,
      allergenNotes: 'Likely contains tree nuts/hazelnut — confirm recipe.',
      notes: 'This month’s special — confirm group, allergens and yield.',
    }),
  ];
}

export function seedStock(flavours: Flavour[]): StockMap {
  const stock: StockMap = {};
  const patterns = [3, 2, 1, 0, 4, 2, 1, 3, 0, 2];
  flavours.forEach((f, i) => {
    const pots = patterns[i % patterns.length]!;
    stock[f.id] = {
      neg20: Math.ceil(pots * 0.6),
      neg14: Math.floor(pots * 0.4),
      bladders: i % 5 === 0 ? 0 : 2 + (i % 4),
      updatedAt: new Date().toISOString(),
    };
  });
  return stock;
}
